# Generated by Django 5.2.8 on 2025-11-28 10:19

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('listing_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('payment_token', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAYMENT_HELD', 'Payment Held'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PAYMENT_HELD', max_length=20)),
                ('dispute_status', models.CharField(choices=[('NONE', 'None'), ('RAISED', 'Raised'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='NONE', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('disputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
                'indexes': [models.Index(fields=['buyer', '-created'], name='orders_orde_buyer_i_b0962d_idx'), models.Index(fields=['seller', '-created'], name='orders_orde_seller__8aab27_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx')],
            },
        ),
    ]
